enableHardenedMode: false

httpTimeout: 60000

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard

networkConcurrency: 16

nodeLinker: node-modules
