//* useFrameNext Types ==============================

import type { FrameNextCallback } from '#types'

//* Global Type Declarations ==============================

declare global {
  // Job --------------------------------

  /**
   * Internal job representation in the scheduler
   */
  interface Job {
    /** Unique identifier */
    id: string
    /** The callback to execute */
    callback: FrameNextCallback
    /** Phase this job belongs to */
    phase: string
    /** Run before these phases/job ids */
    before: Set<string>
    /** Run after these phases/job ids */
    after: Set<string>
    /** Priority within phase (higher first) */
    priority: number
    /** Insertion order for deterministic tie-breaking */
    index: number
    /** Max FPS for this job (undefined = no limit) */
    fps?: number
    /** Drop frames when behind (true) or catch up (false) */
    drop: boolean
    /** Last run timestamp (ms) */
    lastRun?: number
    /** Whether job is enabled */
    enabled: boolean
  }

  // Phase Graph --------------------------------

  /**
   * A node in the phase graph
   */
  interface PhaseNode {
    /** Phase name */
    name: string
    /** Whether this was auto-generated from a before/after constraint */
    isAutoGenerated: boolean
  }

  /**
   * Options for creating a job from hook options
   */
  interface JobOptions {
    id?: string
    phase?: string
    before?: string | string[]
    after?: string | string[]
    priority?: number
    fps?: number
    drop?: boolean
    enabled?: boolean
  }

  // Frame Loop State --------------------------------

  /**
   * Internal frame loop state
   */
  interface FrameLoopState {
    /** Whether the loop is running */
    running: boolean
    /** Current RAF handle */
    rafHandle: number | null
    /** Last frame timestamp (null = uninitialized) */
    lastTime: number | null
    /** Frame counter */
    frameCount: number
    /** Elapsed time since first frame */
    elapsedTime: number
    /** createdAt timestamp */
    createdAt: number
  }

  // Default Phases --------------------------------

  /**
   * Default phase names for the scheduler
   */
  type DefaultPhase = 'start' | 'input' | 'physics' | 'update' | 'render' | 'finish'
}

export {}
