//* useFrameNext Types ==============================

import type { FrameNextCallback } from '#types'

//* Global Type Declarations ==============================

declare global {
  // Job --------------------------------

  /**
   * Internal job representation in the scheduler
   */
  interface Job {
    /** Unique identifier */
    id: string
    /** The callback to execute */
    callback: FrameNextCallback
    /** Phase this job belongs to */
    phase: string
    /** Run before these phases/job ids */
    before: Set<string>
    /** Run after these phases/job ids */
    after: Set<string>
    /** Priority within phase (higher first) */
    priority: number
    /** Insertion order for deterministic tie-breaking */
    index: number
    /** Max FPS for this job (undefined = no limit) */
    fps?: number
    /** Drop frames when behind (true) or catch up (false) */
    drop: boolean
    /** Last run timestamp (ms) */
    lastRun?: number
    /** Whether job is enabled */
    enabled: boolean
    /** Internal flag: system jobs (like default render) don't block user render takeover */
    system?: boolean
  }

  // Phase Graph --------------------------------

  /**
   * A node in the phase graph
   */
  interface PhaseNode {
    /** Phase name */
    name: string
    /** Whether this was auto-generated from a before/after constraint */
    isAutoGenerated: boolean
  }

  /**
   * Options for creating a job from hook options
   */
  interface JobOptions {
    id?: string
    phase?: string
    before?: string | string[]
    after?: string | string[]
    priority?: number
    fps?: number
    drop?: boolean
    enabled?: boolean
  }

  // Frame Loop State --------------------------------

  /**
   * Internal frame loop state
   */
  interface FrameLoopState {
    /** Whether the loop is running */
    running: boolean
    /** Current RAF handle */
    rafHandle: number | null
    /** Last frame timestamp in ms (null = uninitialized) */
    lastTime: number | null
    /** Frame counter */
    frameCount: number
    /** Elapsed time since first frame in ms */
    elapsedTime: number
    /** createdAt timestamp in ms */
    createdAt: number
  }

  // Root Entry --------------------------------

  /**
   * Internal representation of a registered root (Canvas).
   * Tracks jobs and manages rebuild state for this root.
   * @internal
   */
  interface RootEntry {
    /** Unique identifier for this root */
    id: string
    /** Function to get the root's current state. Returns any to support independent mode. */
    getState: () => any
    /** Map of job IDs to Job objects */
    jobs: Map<string, Job>
    /** Cached sorted job list for execution order */
    sortedJobs: Job[]
    /** Whether sortedJobs needs rebuilding */
    needsRebuild: boolean
  }

  /**
   * Internal representation of a global job (deprecated API).
   * Global jobs run once per frame, not per-root.
   * Used by legacy addEffect/addAfterEffect APIs.
   * @internal
   * @deprecated Use useFrame with phases instead
   */
  interface GlobalJob {
    /** Unique identifier for this global job */
    id: string
    /** Callback invoked with RAF timestamp in ms */
    callback: (timestamp: number) => void
  }

  // HMR Support --------------------------------

  /**
   * Hot Module Replacement data structure for preserving scheduler state
   * @internal
   */
  interface HMRData {
    /** Shared data object for storing values across reloads */
    data: Record<string, any>
    /** Optional function to accept HMR updates */
    accept?: () => void
  }

  // Default Phases --------------------------------

  /**
   * Default phase names for the scheduler
   */
  type DefaultPhase = 'start' | 'input' | 'physics' | 'update' | 'render' | 'finish'
}

export {}
