// These values were automatically generated. Do not manually edit this file.
// See scripts/gen-components/

import * as ReactThreeFiber from './types'

export const Primitive = ('primitive' as any) as <T extends Record<string, any>>(
  props: ReactThreeFiber.PrimitiveProps<T>
) => JSX.Element
export const New = ('new' as any) as <T extends new (...args: any[]) => unknown>(
  props: ReactThreeFiber.NewProps<T>
) => JSX.Element

// Automatically generated
export const WebGLMultisampleRenderTarget = 'webGLMultisampleRenderTarget' as 'webGLMultisampleRenderTarget'
export const WebGLCubeRenderTarget = 'webGLCubeRenderTarget' as 'webGLCubeRenderTarget'
export const WebGLRenderTarget = 'webGLRenderTarget' as 'webGLRenderTarget'
export const WebGLRenderer = 'webGLRenderer' as 'webGLRenderer'
export const WebGL1Renderer = 'webGL1Renderer' as 'webGL1Renderer'
export const FogExp2 = 'fogExp2' as 'fogExp2'
export const Fog = 'fog' as 'fog'
export const Scene = 'scene' as 'scene'
export const Sprite = 'sprite' as 'sprite'
export const LOD = 'lOD' as 'lOD'
export const InstancedMesh = 'instancedMesh' as 'instancedMesh'
export const SkinnedMesh = 'skinnedMesh' as 'skinnedMesh'
export const Skeleton = 'skeleton' as 'skeleton'
export const Bone = 'bone' as 'bone'
export const Mesh = 'mesh' as 'mesh'
export const LineSegments = 'lineSegments' as 'lineSegments'
export const LineLoop = 'lineLoop' as 'lineLoop'
export const Line = 'line' as 'line'
export const Points = 'points' as 'points'
export const Group = 'group' as 'group'
export const VideoTexture = 'videoTexture' as 'videoTexture'
export const DataTexture = 'dataTexture' as 'dataTexture'
export const DataTexture2DArray = 'dataTexture2DArray' as 'dataTexture2DArray'
export const DataTexture3D = 'dataTexture3D' as 'dataTexture3D'
export const CompressedTexture = 'compressedTexture' as 'compressedTexture'
export const CubeTexture = 'cubeTexture' as 'cubeTexture'
export const CanvasTexture = 'canvasTexture' as 'canvasTexture'
export const DepthTexture = 'depthTexture' as 'depthTexture'
export const Texture = 'texture' as 'texture'
export const BoxGeometry = 'boxGeometry' as 'boxGeometry'
export const BoxBufferGeometry = 'boxBufferGeometry' as 'boxBufferGeometry'
export const CircleGeometry = 'circleGeometry' as 'circleGeometry'
export const CircleBufferGeometry = 'circleBufferGeometry' as 'circleBufferGeometry'
export const ConeGeometry = 'coneGeometry' as 'coneGeometry'
export const ConeBufferGeometry = 'coneBufferGeometry' as 'coneBufferGeometry'
export const CylinderGeometry = 'cylinderGeometry' as 'cylinderGeometry'
export const CylinderBufferGeometry = 'cylinderBufferGeometry' as 'cylinderBufferGeometry'
export const DodecahedronGeometry = 'dodecahedronGeometry' as 'dodecahedronGeometry'
export const DodecahedronBufferGeometry = 'dodecahedronBufferGeometry' as 'dodecahedronBufferGeometry'
export const EdgesGeometry = 'edgesGeometry' as 'edgesGeometry'
export const ExtrudeGeometry = 'extrudeGeometry' as 'extrudeGeometry'
export const ExtrudeBufferGeometry = 'extrudeBufferGeometry' as 'extrudeBufferGeometry'
export const IcosahedronGeometry = 'icosahedronGeometry' as 'icosahedronGeometry'
export const IcosahedronBufferGeometry = 'icosahedronBufferGeometry' as 'icosahedronBufferGeometry'
export const LatheGeometry = 'latheGeometry' as 'latheGeometry'
export const LatheBufferGeometry = 'latheBufferGeometry' as 'latheBufferGeometry'
export const OctahedronGeometry = 'octahedronGeometry' as 'octahedronGeometry'
export const OctahedronBufferGeometry = 'octahedronBufferGeometry' as 'octahedronBufferGeometry'
export const ParametricGeometry = 'parametricGeometry' as 'parametricGeometry'
export const ParametricBufferGeometry = 'parametricBufferGeometry' as 'parametricBufferGeometry'
export const PlaneGeometry = 'planeGeometry' as 'planeGeometry'
export const PlaneBufferGeometry = 'planeBufferGeometry' as 'planeBufferGeometry'
export const PolyhedronGeometry = 'polyhedronGeometry' as 'polyhedronGeometry'
export const PolyhedronBufferGeometry = 'polyhedronBufferGeometry' as 'polyhedronBufferGeometry'
export const RingGeometry = 'ringGeometry' as 'ringGeometry'
export const RingBufferGeometry = 'ringBufferGeometry' as 'ringBufferGeometry'
export const ShapeGeometry = 'shapeGeometry' as 'shapeGeometry'
export const ShapeBufferGeometry = 'shapeBufferGeometry' as 'shapeBufferGeometry'
export const SphereGeometry = 'sphereGeometry' as 'sphereGeometry'
export const SphereBufferGeometry = 'sphereBufferGeometry' as 'sphereBufferGeometry'
export const TetrahedronGeometry = 'tetrahedronGeometry' as 'tetrahedronGeometry'
export const TetrahedronBufferGeometry = 'tetrahedronBufferGeometry' as 'tetrahedronBufferGeometry'
export const TextGeometry = 'textGeometry' as 'textGeometry'
export const TextBufferGeometry = 'textBufferGeometry' as 'textBufferGeometry'
export const TorusGeometry = 'torusGeometry' as 'torusGeometry'
export const TorusBufferGeometry = 'torusBufferGeometry' as 'torusBufferGeometry'
export const TorusKnotGeometry = 'torusKnotGeometry' as 'torusKnotGeometry'
export const TorusKnotBufferGeometry = 'torusKnotBufferGeometry' as 'torusKnotBufferGeometry'
export const TubeGeometry = 'tubeGeometry' as 'tubeGeometry'
export const TubeBufferGeometry = 'tubeBufferGeometry' as 'tubeBufferGeometry'
export const WireframeGeometry = 'wireframeGeometry' as 'wireframeGeometry'
export const ShadowMaterial = 'shadowMaterial' as 'shadowMaterial'
export const SpriteMaterial = 'spriteMaterial' as 'spriteMaterial'
export const RawShaderMaterial = 'rawShaderMaterial' as 'rawShaderMaterial'
export const ShaderMaterial = 'shaderMaterial' as 'shaderMaterial'
export const PointsMaterial = 'pointsMaterial' as 'pointsMaterial'
export const MeshPhysicalMaterial = 'meshPhysicalMaterial' as 'meshPhysicalMaterial'
export const MeshStandardMaterial = 'meshStandardMaterial' as 'meshStandardMaterial'
export const MeshPhongMaterial = 'meshPhongMaterial' as 'meshPhongMaterial'
export const MeshToonMaterial = 'meshToonMaterial' as 'meshToonMaterial'
export const MeshNormalMaterial = 'meshNormalMaterial' as 'meshNormalMaterial'
export const MeshLambertMaterial = 'meshLambertMaterial' as 'meshLambertMaterial'
export const MeshDepthMaterial = 'meshDepthMaterial' as 'meshDepthMaterial'
export const MeshDistanceMaterial = 'meshDistanceMaterial' as 'meshDistanceMaterial'
export const MeshBasicMaterial = 'meshBasicMaterial' as 'meshBasicMaterial'
export const MeshMatcapMaterial = 'meshMatcapMaterial' as 'meshMatcapMaterial'
export const LineDashedMaterial = 'lineDashedMaterial' as 'lineDashedMaterial'
export const LineBasicMaterial = 'lineBasicMaterial' as 'lineBasicMaterial'
export const Material = 'material' as 'material'
export const AnimationLoader = 'animationLoader' as 'animationLoader'
export const CompressedTextureLoader = 'compressedTextureLoader' as 'compressedTextureLoader'
export const DataTextureLoader = 'dataTextureLoader' as 'dataTextureLoader'
export const CubeTextureLoader = 'cubeTextureLoader' as 'cubeTextureLoader'
export const TextureLoader = 'textureLoader' as 'textureLoader'
export const ObjectLoader = 'objectLoader' as 'objectLoader'
export const MaterialLoader = 'materialLoader' as 'materialLoader'
export const BufferGeometryLoader = 'bufferGeometryLoader' as 'bufferGeometryLoader'
export const LoadingManager = 'loadingManager' as 'loadingManager'
export const ImageLoader = 'imageLoader' as 'imageLoader'
export const ImageBitmapLoader = 'imageBitmapLoader' as 'imageBitmapLoader'
export const FontLoader = 'fontLoader' as 'fontLoader'
export const FileLoader = 'fileLoader' as 'fileLoader'
export const Loader = 'loader' as 'loader'
export const LoaderUtils = 'loaderUtils' as 'loaderUtils'
export const AudioLoader = 'audioLoader' as 'audioLoader'
export const SpotLightShadow = 'spotLightShadow' as 'spotLightShadow'
export const SpotLight = 'spotLight' as 'spotLight'
export const PointLight = 'pointLight' as 'pointLight'
export const PointLightShadow = 'pointLightShadow' as 'pointLightShadow'
export const RectAreaLight = 'rectAreaLight' as 'rectAreaLight'
export const HemisphereLight = 'hemisphereLight' as 'hemisphereLight'
export const DirectionalLightShadow = 'directionalLightShadow' as 'directionalLightShadow'
export const DirectionalLight = 'directionalLight' as 'directionalLight'
export const AmbientLight = 'ambientLight' as 'ambientLight'
export const LightShadow = 'lightShadow' as 'lightShadow'
export const Light = 'light' as 'light'
export const AmbientLightProbe = 'ambientLightProbe' as 'ambientLightProbe'
export const HemisphereLightProbe = 'hemisphereLightProbe' as 'hemisphereLightProbe'
export const LightProbe = 'lightProbe' as 'lightProbe'
export const StereoCamera = 'stereoCamera' as 'stereoCamera'
export const PerspectiveCamera = 'perspectiveCamera' as 'perspectiveCamera'
export const OrthographicCamera = 'orthographicCamera' as 'orthographicCamera'
export const CubeCamera = 'cubeCamera' as 'cubeCamera'
export const ArrayCamera = 'arrayCamera' as 'arrayCamera'
export const Camera = 'camera' as 'camera'
export const AudioListener = 'audioListener' as 'audioListener'
export const PositionalAudio = 'positionalAudio' as 'positionalAudio'
export const AudioAnalyser = 'audioAnalyser' as 'audioAnalyser'
export const Audio = 'audio' as 'audio'
export const VectorKeyframeTrack = 'vectorKeyframeTrack' as 'vectorKeyframeTrack'
export const StringKeyframeTrack = 'stringKeyframeTrack' as 'stringKeyframeTrack'
export const QuaternionKeyframeTrack = 'quaternionKeyframeTrack' as 'quaternionKeyframeTrack'
export const NumberKeyframeTrack = 'numberKeyframeTrack' as 'numberKeyframeTrack'
export const ColorKeyframeTrack = 'colorKeyframeTrack' as 'colorKeyframeTrack'
export const BooleanKeyframeTrack = 'booleanKeyframeTrack' as 'booleanKeyframeTrack'
export const PropertyMixer = 'propertyMixer' as 'propertyMixer'
export const PropertyBinding = 'propertyBinding' as 'propertyBinding'
export const KeyframeTrack = 'keyframeTrack' as 'keyframeTrack'
export const AnimationObjectGroup = 'animationObjectGroup' as 'animationObjectGroup'
export const AnimationMixer = 'animationMixer' as 'animationMixer'
export const AnimationClip = 'animationClip' as 'animationClip'
export const AnimationAction = 'animationAction' as 'animationAction'
export const Uniform = 'uniform' as 'uniform'
export const InstancedBufferGeometry = 'instancedBufferGeometry' as 'instancedBufferGeometry'
export const BufferGeometry = 'bufferGeometry' as 'bufferGeometry'
export const Geometry = 'geometry' as 'geometry'
export const InterleavedBufferAttribute = 'interleavedBufferAttribute' as 'interleavedBufferAttribute'
export const InstancedInterleavedBuffer = 'instancedInterleavedBuffer' as 'instancedInterleavedBuffer'
export const InterleavedBuffer = 'interleavedBuffer' as 'interleavedBuffer'
export const InstancedBufferAttribute = 'instancedBufferAttribute' as 'instancedBufferAttribute'
export const BufferAttribute = 'bufferAttribute' as 'bufferAttribute'

/**
 * @deprecated Int8Attribute is deprecated in THREE
 */
export const Int8Attribute = 'int8Attribute' as 'int8Attribute'

/**
 * @deprecated Uint8Attribute is deprecated in THREE
 */
export const Uint8Attribute = 'uint8Attribute' as 'uint8Attribute'

/**
 * @deprecated Uint8ClampedAttribute is deprecated in THREE
 */
export const Uint8ClampedAttribute = 'uint8ClampedAttribute' as 'uint8ClampedAttribute'

/**
 * @deprecated Int16Attribute is deprecated in THREE
 */
export const Int16Attribute = 'int16Attribute' as 'int16Attribute'

/**
 * @deprecated Uint16Attribute is deprecated in THREE
 */
export const Uint16Attribute = 'uint16Attribute' as 'uint16Attribute'

/**
 * @deprecated Int32Attribute is deprecated in THREE
 */
export const Int32Attribute = 'int32Attribute' as 'int32Attribute'

/**
 * @deprecated Uint32Attribute is deprecated in THREE
 */
export const Uint32Attribute = 'uint32Attribute' as 'uint32Attribute'

/**
 * @deprecated Float32Attribute is deprecated in THREE
 */
export const Float32Attribute = 'float32Attribute' as 'float32Attribute'

/**
 * @deprecated Float64Attribute is deprecated in THREE
 */
export const Float64Attribute = 'float64Attribute' as 'float64Attribute'
export const Int8BufferAttribute = 'int8BufferAttribute' as 'int8BufferAttribute'
export const Uint8BufferAttribute = 'uint8BufferAttribute' as 'uint8BufferAttribute'
export const Uint8ClampedBufferAttribute = 'uint8ClampedBufferAttribute' as 'uint8ClampedBufferAttribute'
export const Int16BufferAttribute = 'int16BufferAttribute' as 'int16BufferAttribute'
export const Uint16BufferAttribute = 'uint16BufferAttribute' as 'uint16BufferAttribute'
export const Int32BufferAttribute = 'int32BufferAttribute' as 'int32BufferAttribute'
export const Uint32BufferAttribute = 'uint32BufferAttribute' as 'uint32BufferAttribute'
export const Float32BufferAttribute = 'float32BufferAttribute' as 'float32BufferAttribute'
export const Float64BufferAttribute = 'float64BufferAttribute' as 'float64BufferAttribute'
export const Face3 = 'face3' as 'face3'
export const Object3D = 'object3D' as 'object3D'
export const Raycaster = 'raycaster' as 'raycaster'
export const Layers = 'layers' as 'layers'
export const EventDispatcher = 'eventDispatcher' as 'eventDispatcher'
export const DirectGeometry = 'directGeometry' as 'directGeometry'
export const Clock = 'clock' as 'clock'
export const QuaternionLinearInterpolant = 'quaternionLinearInterpolant' as 'quaternionLinearInterpolant'
export const LinearInterpolant = 'linearInterpolant' as 'linearInterpolant'
export const DiscreteInterpolant = 'discreteInterpolant' as 'discreteInterpolant'
export const CubicInterpolant = 'cubicInterpolant' as 'cubicInterpolant'
export const Interpolant = 'interpolant' as 'interpolant'
export const Triangle = 'triangle' as 'triangle'
export const Spherical = 'spherical' as 'spherical'
export const Cylindrical = 'cylindrical' as 'cylindrical'
export const Plane = 'plane' as 'plane'
export const Frustum = 'frustum' as 'frustum'
export const Sphere = 'sphere' as 'sphere'
export const Ray = 'ray' as 'ray'
export const Matrix4 = 'matrix4' as 'matrix4'
export const Matrix3 = 'matrix3' as 'matrix3'
export const Box3 = 'box3' as 'box3'
export const Box2 = 'box2' as 'box2'
export const Line3 = 'line3' as 'line3'
export const Euler = 'euler' as 'euler'
export const Vector4 = 'vector4' as 'vector4'
export const Vector3 = 'vector3' as 'vector3'
export const Vector2 = 'vector2' as 'vector2'
export const Quaternion = 'quaternion' as 'quaternion'
export const Color = 'color' as 'color'
export const SphericalHarmonics3 = 'sphericalHarmonics3' as 'sphericalHarmonics3'
export const ImmediateRenderObject = 'immediateRenderObject' as 'immediateRenderObject'
export const SpotLightHelper = 'spotLightHelper' as 'spotLightHelper'
export const SkeletonHelper = 'skeletonHelper' as 'skeletonHelper'
export const PointLightHelper = 'pointLightHelper' as 'pointLightHelper'
export const HemisphereLightHelper = 'hemisphereLightHelper' as 'hemisphereLightHelper'
export const GridHelper = 'gridHelper' as 'gridHelper'
export const PolarGridHelper = 'polarGridHelper' as 'polarGridHelper'
export const DirectionalLightHelper = 'directionalLightHelper' as 'directionalLightHelper'
export const CameraHelper = 'cameraHelper' as 'cameraHelper'
export const BoxHelper = 'boxHelper' as 'boxHelper'
export const Box3Helper = 'box3Helper' as 'box3Helper'
export const PlaneHelper = 'planeHelper' as 'planeHelper'
export const ArrowHelper = 'arrowHelper' as 'arrowHelper'
export const AxesHelper = 'axesHelper' as 'axesHelper'
export const ArcCurve = 'arcCurve' as 'arcCurve'
export const CatmullRomCurve3 = 'catmullRomCurve3' as 'catmullRomCurve3'
export const CubicBezierCurve = 'cubicBezierCurve' as 'cubicBezierCurve'
export const CubicBezierCurve3 = 'cubicBezierCurve3' as 'cubicBezierCurve3'
export const EllipseCurve = 'ellipseCurve' as 'ellipseCurve'
export const LineCurve = 'lineCurve' as 'lineCurve'
export const LineCurve3 = 'lineCurve3' as 'lineCurve3'
export const QuadraticBezierCurve = 'quadraticBezierCurve' as 'quadraticBezierCurve'
export const QuadraticBezierCurve3 = 'quadraticBezierCurve3' as 'quadraticBezierCurve3'
export const SplineCurve = 'splineCurve' as 'splineCurve'
export const Shape = 'shape' as 'shape'
export const Path = 'path' as 'path'
export const ShapePath = 'shapePath' as 'shapePath'
export const Font = 'font' as 'font'
export const CurvePath = 'curvePath' as 'curvePath'
export const Curve = 'curve' as 'curve'
export const PMREMGenerator = 'pMREMGenerator' as 'pMREMGenerator'
export const WebGLBufferRenderer = 'webGLBufferRenderer' as 'webGLBufferRenderer'
export const WebGLCapabilities = 'webGLCapabilities' as 'webGLCapabilities'
export const WebGLClipping = 'webGLClipping' as 'webGLClipping'
export const WebGLExtensions = 'webGLExtensions' as 'webGLExtensions'
export const WebGLGeometries = 'webGLGeometries' as 'webGLGeometries'
export const WebGLIndexedBufferRenderer = 'webGLIndexedBufferRenderer' as 'webGLIndexedBufferRenderer'
export const WebGLInfo = 'webGLInfo' as 'webGLInfo'
export const WebGLLights = 'webGLLights' as 'webGLLights'
export const WebGLObjects = 'webGLObjects' as 'webGLObjects'
export const WebGLProgram = 'webGLProgram' as 'webGLProgram'
export const WebGLPrograms = 'webGLPrograms' as 'webGLPrograms'
export const WebGLProperties = 'webGLProperties' as 'webGLProperties'
export const WebGLRenderList = 'webGLRenderList' as 'webGLRenderList'
export const WebGLRenderLists = 'webGLRenderLists' as 'webGLRenderLists'
export const WebGLShader = 'webGLShader' as 'webGLShader'
export const WebGLShadowMap = 'webGLShadowMap' as 'webGLShadowMap'
export const WebGLColorBuffer = 'webGLColorBuffer' as 'webGLColorBuffer'
export const WebGLDepthBuffer = 'webGLDepthBuffer' as 'webGLDepthBuffer'
export const WebGLStencilBuffer = 'webGLStencilBuffer' as 'webGLStencilBuffer'
export const WebGLState = 'webGLState' as 'webGLState'
export const WebGLTextures = 'webGLTextures' as 'webGLTextures'
export const WebGLUniforms = 'webGLUniforms' as 'webGLUniforms'
export const XRWebGLLayer = 'xRWebGLLayer' as 'xRWebGLLayer'
export const XRRigidTransform = 'xRRigidTransform' as 'xRRigidTransform'
export const XRRay = 'xRRay' as 'xRRay'
export const XRHand = 'xRHand' as 'xRHand'
export const WebXRController = 'webXRController' as 'webXRController'
export const WebXRManager = 'webXRManager' as 'webXRManager'

/**
 * @deprecated MultiMaterial is deprecated in THREE
 */
export const MultiMaterial = 'multiMaterial' as 'multiMaterial'
