import React from 'react'

import { Canvas } from './targets/web'

const _elements = (
  <Canvas>
    <audio />
    <audioListener />
    <positionalAudio />
    <mesh position={[0, 0, 0]}>
      <primitive object="TODO?" />
    </mesh>
    <scene />
    <sprite />
    <lOD />
    <skinnedMesh />
    <skeleton />
    <bone />
    <lineSegments />
    <lineLoop />
    <line />
    <points />
    <group />
    <immediateRenderObject />
    <camera />
    <perspectiveCamera />
    <orthographicCamera />
    <cubeCamera />
    <arrayCamera />
    <geometry />
    <instancedBufferGeometry />
    <bufferGeometry />
    <boxBufferGeometry />
    <circleBufferGeometry />
    <coneBufferGeometry />
    <cylinderBufferGeometry />
    <dodecahedronBufferGeometry />
    <extrudeBufferGeometry />
    <icosahedronBufferGeometry />
    <latheBufferGeometry />
    <octahedronBufferGeometry />
    <parametricBufferGeometry />
    <planeBufferGeometry />
    <polyhedronBufferGeometry />
    <ringBufferGeometry />
    <shapeBufferGeometry />
    <sphereBufferGeometry />
    <tetrahedronBufferGeometry />
    <textBufferGeometry />
    <torusBufferGeometry />
    <torusKnotBufferGeometry />
    <tubeBufferGeometry />
    <wireframeGeometry />
    <parametricGeometry />
    <tetrahedronGeometry />
    <octahedronGeometry />
    <icosahedronGeometry />
    <dodecahedronGeometry />
    <polyhedronGeometry />
    <tubeGeometry />
    <torusKnotGeometry />
    <torusGeometry />
    <textGeometry />
    <sphereGeometry />
    <ringGeometry />
    <planeGeometry />
    <latheGeometry />
    <shapeGeometry />
    <extrudeGeometry />
    <edgesGeometry />
    <coneGeometry />
    <cylinderGeometry />
    <circleGeometry />
    <boxGeometry />
    <material />
    <shadowMaterial />
    <spriteMaterial />
    <rawShaderMaterial />
    <shaderMaterial />
    <pointsMaterial />
    <meshPhysicalMaterial />
    <meshStandardMaterial />
    <meshPhongMaterial />
    <meshToonMaterial />
    <meshNormalMaterial />
    <meshLambertMaterial />
    <meshDepthMaterial />
    <meshDistanceMaterial />
    <meshBasicMaterial />
    <meshMatcapMaterial />
    <lineDashedMaterial />
    <lineBasicMaterial />
    <object />
    <light />
    <spotLightShadow />
    <spotLight />
    <pointLight />
    <rectAreaLight />
    <hemisphereLight />
    <directionalLightShadow />
    <directionalLight />
    <ambientLight />
    <lightShadow />
    <ambientLightProbe />
    <hemisphereLightProbe />
    <lightProbe />
    <vertexNormalsHelper />
    <spotLightHelper />
    <skeletonHelper />
    <pointLightHelper />
    <rectAreaLightHelper />
    <hemisphereLightHelper />
    <gridHelper />
    <polarGridHelper />
    <positionalAudioHelper />
    <faceNormalsHelper />
    <directionalLightHelper />
    <cameraHelper />
    <boxHelper />
    <box3Helper />
    <planeHelper />
    <arrowHelper />
    <axesHelper />
    <texture />
    <videoTexture />
    <dataTexture />
    <dataTexture3D />
    <compressedTexture />
    <cubeTexture />
    <canvasTexture />
    <depthTexture />
    <raycaster />
    <vector2 />
    <vector3 />
    <vector4 />
    <euler />
    <matrix3 />
    <matrix4 />
    <quaternion />
  </Canvas>
)
