name: V9 Prerelease Builds

on:
  push:
    branches:
      - v9

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  canary_release:
    name: V9 Prerelase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Create .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Snapshot Release
        run: |
          yarn changeset version --snapshot next
          yarn release --no-git-tag --snapshot next --tag next
